name: Node.js CI

on:
    push:
        branches: [ main, staging ]
    pull_request:
        branches: [ main, staging ]

jobs:
    build:

        runs-on: ubuntu-latest

        services:
            mongodb:
                image: mongo:latest
                env:
                    MONGO_INITDB_DATABASE: matching_service_database
                ports:
                - 27017:27017

        steps:
        -   name: Checkout repository code
            uses: actions/checkout@v2
        -   name: Use Node.js 14
            uses: actions/setup-node@v2
            with:
                node-version: 14.x
        -   name: Install dependencies
            run: npm ci
        -   run: npm run build --if-present
        -   name: Run testing
            run: npm test
        -   name: Upload coverage to Codecov
            uses: codecov/codecov-action@v1